### ISSUE TITLE
Patch error

### ISSUE THREAD

**Issue by WoWich2005** [YaAlex3/patcher-oss#11]
Когда я пытаюсь пропатчить свой boot.img программа выдает ошибки:
INFO: Found 7-Zip at: C:\Program Files\7-Zip\7z.exe
Traceback (most recent call last):
  File "C:\Users\Владимир\Desktop\patcher-oss-main\main.py", line 201, in <module>
    main()
  File "C:\Users\Владимир\Desktop\patcher-oss-main\main.py", line 56, in main
    BootWork(in_fn)
  File "C:\Users\Владимир\Desktop\patcher-oss-main\main.py", line 89, in __init__
    p = Patch(zimg_fn)
  File "C:\Users\Владимир\Desktop\patcher-oss-main\main.py", line 112, in __init__
    self.split_zimg(zimg_fn)
  File "C:\Users\Владимир\Desktop\patcher-oss-main\main.py", line 135, in split_zimg
    d = mmap.mmap(zimg_file.fileno(), zimg_size, access=mmap.ACCESS_READ)
OSError: [WinError 8] Недостаточно ресурсов памяти для обработки этой команды

Раньше, когда я пытался распаковать с помощью сторонней утилиты она жаловалась на отсуствие рамдиска, но когда ссылка вела на сайт с этой утилитой у меня получилось пропатчить своё ядро

Модель телефона: Redmi 8a
Ссылка на ядро: https://drive.google.com/file/d/11cUZT4GAjT6530BIXR6FJPmQrjAQ5vCK/view?usp=sharing

**Comment by WoWich2005** [comment]
На arch linux таже ошибка

**Comment by WoWich2005** [comment]
Ошибка происходила из-за неправильного boot.img все таки
boot.img я достал с помощью adb shell dd if=/dev/block/by-name/boot of=/sdcard/boot.img
А надо было adb shell dd if=/dev/block/bootdevice/by-name/boot of=/sdcard/boot.img
