### ISSUE TITLE
Can't patch latest Xiaomi Redmi 8A kernel

### ISSUE THREAD

**Issue by khaalidrafi** [YaAlex3/patcher-oss#6]
```
Traceback (most recent call last):
  File "/tmp/patcher-oss/./main.py", line 138, in <module>
    main()
  File "/tmp/patcher-oss/./main.py", line 36, in main
    Patch(zimg_fn)
  File "/tmp/patcher-oss/./main.py", line 49, in __init__
    self.split_zimg(zimg_fn)
  File "/tmp/patcher-oss/./main.py", line 68, in split_zimg
    raise Exception(
Exception: ERROR: Didn't find IMG magic number
```

**Comment by YaAlex3** [comment]
hey, can you please attach said kernel to the issue, I'll try to replicate when I'm free

**Comment by krafi99** [comment]
> hey, can you please attach said kernel to the issue, I'll try to replicate when I'm free

**Comment by cnekmp** [comment]
Same issue on Mi9T Pro (xiaomi.eu ROM):

```
[user@unknown ~/git/patcher-oss]$ python main.py ~/boot.img
Traceback (most recent call last):
  File "/home/user/git/patcher-oss/main.py", line 138, in <module>
    main()
  File "/home/user/git/patcher-oss/main.py", line 36, in main
    Patch(zimg_fn)
  File "/home/user/git/patcher-oss/main.py", line 49, in __init__
    self.split_zimg(zimg_fn)
  File "/home/user/git/patcher-oss/main.py", line 68, in split_zimg
    raise Exception(
Exception: ERROR: Didn't find IMG magic number


```

[boot.img.zip](https://github.com/YaAlex3/patcher-oss/files/6400666/boot.img.zip)

**Comment by YaAlex3** [comment]
you're not supposed to use it on 64bit kernels. Re-read the readme, hope i give enough context. Closed.
